services:

  postgres:
    image: postgres:16
    container_name: budgetsetu_postgres
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      POSTGRES_USER: budgetsetu_user
      POSTGRES_PASSWORD: your_strong_password_here
      POSTGRES_DB: budgetsetu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budgetsetu_user -d budgetsetu"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: budgetsetu_mongo
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: budgetsetu_redis
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:
  redis_data:
